# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/serosh/projects/middle_out

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/serosh/projects/middle_out

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serosh/projects/middle_out/CMakeFiles /home/serosh/projects/middle_out//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/serosh/projects/middle_out/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named middle_out

# Build rule for target.
middle_out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 middle_out
.PHONY : middle_out

# fast build rule for target.
middle_out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/build
.PHONY : middle_out/fast

src/bitstream.o: src/bitstream.cpp.o
.PHONY : src/bitstream.o

# target to build an object file
src/bitstream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/bitstream.cpp.o
.PHONY : src/bitstream.cpp.o

src/bitstream.i: src/bitstream.cpp.i
.PHONY : src/bitstream.i

# target to preprocess a source file
src/bitstream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/bitstream.cpp.i
.PHONY : src/bitstream.cpp.i

src/bitstream.s: src/bitstream.cpp.s
.PHONY : src/bitstream.s

# target to generate assembly for a file
src/bitstream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/bitstream.cpp.s
.PHONY : src/bitstream.cpp.s

src/compressor.o: src/compressor.cpp.o
.PHONY : src/compressor.o

# target to build an object file
src/compressor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/compressor.cpp.o
.PHONY : src/compressor.cpp.o

src/compressor.i: src/compressor.cpp.i
.PHONY : src/compressor.i

# target to preprocess a source file
src/compressor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/compressor.cpp.i
.PHONY : src/compressor.cpp.i

src/compressor.s: src/compressor.cpp.s
.PHONY : src/compressor.s

# target to generate assembly for a file
src/compressor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/compressor.cpp.s
.PHONY : src/compressor.cpp.s

src/middle_out.o: src/middle_out.cpp.o
.PHONY : src/middle_out.o

# target to build an object file
src/middle_out.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/middle_out.cpp.o
.PHONY : src/middle_out.cpp.o

src/middle_out.i: src/middle_out.cpp.i
.PHONY : src/middle_out.i

# target to preprocess a source file
src/middle_out.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/middle_out.cpp.i
.PHONY : src/middle_out.cpp.i

src/middle_out.s: src/middle_out.cpp.s
.PHONY : src/middle_out.s

# target to generate assembly for a file
src/middle_out.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/middle_out.cpp.s
.PHONY : src/middle_out.cpp.s

src/rans.o: src/rans.cpp.o
.PHONY : src/rans.o

# target to build an object file
src/rans.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/rans.cpp.o
.PHONY : src/rans.cpp.o

src/rans.i: src/rans.cpp.i
.PHONY : src/rans.i

# target to preprocess a source file
src/rans.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/rans.cpp.i
.PHONY : src/rans.cpp.i

src/rans.s: src/rans.cpp.s
.PHONY : src/rans.s

# target to generate assembly for a file
src/rans.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/rans.cpp.s
.PHONY : src/rans.cpp.s

src/suffix_array.o: src/suffix_array.cpp.o
.PHONY : src/suffix_array.o

# target to build an object file
src/suffix_array.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/suffix_array.cpp.o
.PHONY : src/suffix_array.cpp.o

src/suffix_array.i: src/suffix_array.cpp.i
.PHONY : src/suffix_array.i

# target to preprocess a source file
src/suffix_array.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/suffix_array.cpp.i
.PHONY : src/suffix_array.cpp.i

src/suffix_array.s: src/suffix_array.cpp.s
.PHONY : src/suffix_array.s

# target to generate assembly for a file
src/suffix_array.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/middle_out.dir/build.make CMakeFiles/middle_out.dir/src/suffix_array.cpp.s
.PHONY : src/suffix_array.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... middle_out"
	@echo "... src/bitstream.o"
	@echo "... src/bitstream.i"
	@echo "... src/bitstream.s"
	@echo "... src/compressor.o"
	@echo "... src/compressor.i"
	@echo "... src/compressor.s"
	@echo "... src/middle_out.o"
	@echo "... src/middle_out.i"
	@echo "... src/middle_out.s"
	@echo "... src/rans.o"
	@echo "... src/rans.i"
	@echo "... src/rans.s"
	@echo "... src/suffix_array.o"
	@echo "... src/suffix_array.i"
	@echo "... src/suffix_array.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

